name: Bug Report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "Prerequisites"
  - type: checkboxes
    validations:
      required: true
    attributes:
      label: "Check before submitting"
      description: "Before submitting the issue, please check the following:"
      options:
        - label: "I have searched the issue tracker for the same problem"
        - label: "I have updated all software to the latest versions"
       

  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the Bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: "Step To Reproduce"
      description: "Steps to reproduce the behavior."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
   
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here."
