name: Bug Report
description: Report a bug in the tobac library.
labels: [bug]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Tobac issue checks
      options:
        - label: >
            Have you checked if the issue has already been reported?
          required: true
  - type: textarea
    id: example
    attributes:
      label: How to reproduce the bug
      placeholder: >
        1.
        
        2.
        
        3.

        
        ...
      description: >
        Please describe how to reproduce the bug in as much detail as possible.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: >
        Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
    validations:
      required: true
