name: Ask a question
description: Ask a general question about tobac
labels: ["question"]

body:
  - type: checkboxes
    attributes:
      label: "Before submitting the question, please check the following"
      options:
        - label: "I have searched the issue tracker for similar questions"
    validations:
      required: true
        
  - type: textarea
    id: question
    attributes:
      label: "Describe your question with as much detail as possible"
      placeholder: "The more details, the better"
      description: "What would you like to know?"
