name: Release
description: Prepare new release for the tobac library.
labels: [release]

body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checklist for releasing vX.X.X
      options:
        - label: >
            Bump version in `__init__.py `in `X`
        - label: >
            Add new contributors to vX.X.X
        - label: >
            Add changelog in `X`
        - label: >
            Merge `X` into `main`
        - label: >
            Delete `X` branch
        - label: >
            Create release
        - label: >
            Push release to conda-forge
        - label: >
            E-mail tobac mailing list
